[project]
name = "lazydh"
version = "1.0.1"
description = "Convert .pdfs of Daggerheart statblocks to your favorite text-based storage format."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pymupdf4llm>=1.27.2.3",
    "pymupdf>=1.27.2.3",
    "typer>=0.25.1",
    "regex>=2026.5.9",
]
[project.scripts]
lazydh = "lazydh.cli:app"
[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-cov>=6.0.0",
]
[build-system]
requires = ['uv_build>=0.8.3, <0.9.0']
build-backend = "uv_build"
[tool.uv.build-backend]
module-name = "lazydh"
module-root = ""
[tool.pytest.ini_options]
testpaths = ['tests']
filterwarnings = [
    "ignore::DeprecationWarning"
]
